/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineexam;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author apple
 */
public class Dashboard_2 extends javax.swing.JFrame {

    /**
     * Creates new form MainLogic
     */
    public Dashboard_2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        B2 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        BranchField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        B3 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        B4 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        A4 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        TotalInvig = new javax.swing.JTextField();
        AllInvigilators = new javax.swing.JButton();
        InvigProf = new javax.swing.JButton();
        ProfCount = new javax.swing.JTextField();
        AssoCount = new javax.swing.JTextField();
        InvigAsso = new javax.swing.JButton();
        AssistCount = new javax.swing.JTextField();
        InvigAssist = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(51, 51, 51));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(102, 255, 153));
        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("YEAR 4");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 322, 162, 51));

        B2.setText("Sec B");
        B2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B2MouseClicked(evt);
            }
        });
        getContentPane().add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 485, 218, 65));

        C2.setText("Sec C");
        C2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C2MouseClicked(evt);
            }
        });
        getContentPane().add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 556, 218, 63));

        D2.setText("Sec D");
        D2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D2MouseClicked(evt);
            }
        });
        getContentPane().add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 625, 218, 65));

        E2.setText("Sec E");
        E2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E2MouseClicked(evt);
            }
        });
        getContentPane().add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 696, 218, 66));

        F3.setText("Sec F");
        F3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F3MouseClicked(evt);
            }
        });
        getContentPane().add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 768, 234, 64));

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        BranchField.setBackground(new java.awt.Color(153, 0, 255));
        BranchField.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        BranchField.setForeground(new java.awt.Color(255, 255, 255));
        BranchField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        BranchField.setText("jTextField1");
        BranchField.setBorder(null);
        BranchField.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                BranchFieldHierarchyChanged(evt);
            }
        });

        jButton1.setText("-->");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setText("<--");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BranchField, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 572, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(jButton1))
                    .addComponent(BranchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 971, -1));

        jLabel4.setBackground(new java.awt.Color(102, 255, 153));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("YEAR 3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 324, 162, 49));

        B3.setText("Sec B");
        B3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B3MouseClicked(evt);
            }
        });
        getContentPane().add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 485, 234, 65));

        C3.setText("Sec C");
        C3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C3MouseClicked(evt);
            }
        });
        getContentPane().add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 556, 234, 63));

        D3.setText("Sec D");
        D3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D3MouseClicked(evt);
            }
        });
        getContentPane().add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 622, 234, 66));

        E3.setText("Sec E");
        E3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E3MouseClicked(evt);
            }
        });
        getContentPane().add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 696, 234, 66));

        F4.setText("Sec F");
        F4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F4MouseClicked(evt);
            }
        });
        getContentPane().add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 768, 258, 64));

        jLabel5.setBackground(new java.awt.Color(102, 255, 153));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("YEAR 2");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, 162, 53));

        B4.setText("Sec B");
        B4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                B4MouseClicked(evt);
            }
        });
        getContentPane().add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 485, 258, 65));

        C4.setText("Sec C");
        C4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                C4MouseClicked(evt);
            }
        });
        getContentPane().add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 552, 258, 63));

        D4.setText("Sec D");
        D4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                D4MouseClicked(evt);
            }
        });
        getContentPane().add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 621, 258, 69));

        E4.setText("Sec E");
        E4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                E4MouseClicked(evt);
            }
        });
        getContentPane().add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(507, 696, 258, 66));

        F2.setText("Sec F");
        F2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                F2MouseClicked(evt);
            }
        });
        getContentPane().add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 768, 218, 64));

        A4.setText("Sec A");
        A4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A4MouseClicked(evt);
            }
        });
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });

        A3.setText("Sec A");
        A3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A3MouseClicked(evt);
            }
        });
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });

        A2.setText("Sec A");
        A2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                A2MouseClicked(evt);
            }
        });
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });

        TotalInvig.setBackground(new java.awt.Color(51, 51, 51));
        TotalInvig.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        TotalInvig.setForeground(new java.awt.Color(255, 51, 255));
        TotalInvig.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        TotalInvig.setText(".");
        TotalInvig.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                TotalInvigHierarchyChanged(evt);
            }
        });

        AllInvigilators.setBackground(new java.awt.Color(238, 177, 244));
        AllInvigilators.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        AllInvigilators.setText("Invigilators Assigned");
        AllInvigilators.setOpaque(true);
        AllInvigilators.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AllInvigilatorsMouseClicked(evt);
            }
        });

        InvigProf.setBackground(new java.awt.Color(238, 72, 64));
        InvigProf.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InvigProf.setText("Professor Invigilators");
        InvigProf.setOpaque(true);
        InvigProf.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvigProfMouseClicked(evt);
            }
        });

        ProfCount.setBackground(new java.awt.Color(51, 51, 51));
        ProfCount.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        ProfCount.setForeground(new java.awt.Color(255, 0, 51));
        ProfCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ProfCount.setText(".");
        ProfCount.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                ProfCountComponentAdded(evt);
            }
        });
        ProfCount.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                ProfCountHierarchyChanged(evt);
            }
        });
        ProfCount.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                ProfCountComponentShown(evt);
            }
        });

        AssoCount.setBackground(new java.awt.Color(51, 51, 51));
        AssoCount.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        AssoCount.setForeground(new java.awt.Color(0, 204, 204));
        AssoCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AssoCount.setText(".");
        AssoCount.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                AssoCountComponentAdded(evt);
            }
        });
        AssoCount.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                AssoCountHierarchyChanged(evt);
            }
        });

        InvigAsso.setBackground(new java.awt.Color(72, 227, 204));
        InvigAsso.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InvigAsso.setText("Associate invigilators");
        InvigAsso.setOpaque(true);
        InvigAsso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvigAssoMouseClicked(evt);
            }
        });

        AssistCount.setBackground(new java.awt.Color(51, 51, 51));
        AssistCount.setFont(new java.awt.Font("Trebuchet MS", 0, 36)); // NOI18N
        AssistCount.setForeground(new java.awt.Color(0, 255, 102));
        AssistCount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AssistCount.setText(".");
        AssistCount.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                AssistCountComponentAdded(evt);
            }
        });
        AssistCount.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                AssistCountHierarchyChanged(evt);
            }
        });

        InvigAssist.setBackground(new java.awt.Color(22, 235, 128));
        InvigAssist.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        InvigAssist.setText("Assistant Invigilators");
        InvigAssist.setOpaque(true);
        InvigAssist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InvigAssistMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(210, 210, 210))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(AllInvigilators, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(InvigProf, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InvigAsso, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(InvigAssist, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addComponent(TotalInvig, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(131, 131, 131)
                .addComponent(ProfCount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142)
                .addComponent(AssoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(AssistCount, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(162, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AllInvigilators, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvigProf, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvigAsso, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InvigAssist, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TotalInvig, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProfCount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssoCount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AssistCount, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(102, 102, 102)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A4, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(381, 381, 381))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 5, 970, 850));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A2ActionPerformed

    private void E2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E2MouseClicked
        // TODO add your handling code here:
      
        clickEvents.section="E";
        clickEvents.semester=3;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
         dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
        
        
        
       
        
        
//         static  String section;
//     static String sectionCoordinator;
//     static String examDate;
//     static String examName1;
//     static String examName2;
//     static String examName3;
//     static String examName4;
//     static String examName5;
//     static String examName6;
//     static  String invig1;
//      static String invig2;
//     static String invig3;
//     static String invig4;
        
    }//GEN-LAST:event_E2MouseClicked

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A3ActionPerformed

    private void E3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E3MouseClicked
        // TODO add your handling code here:
         clickEvents.section="E";
        clickEvents.semester=5;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
           dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_E3MouseClicked

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_A4ActionPerformed

    private void E4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_E4MouseClicked
        // TODO add your handling code here:
        clickEvents.section="E";
        clickEvents.semester=7;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
           dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_E4MouseClicked

    private void A2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A2MouseClicked
        // TODO add your handling code here:
        clickEvents.section="A";
        clickEvents.semester=3;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
           dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_A2MouseClicked

    private void B2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B2MouseClicked
        // TODO add your handling code here:
           clickEvents.section="B";
        clickEvents.semester=3;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
           dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_B2MouseClicked

    private void C2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C2MouseClicked
        // TODO add your handling code here:
           clickEvents.section="C";
        clickEvents.semester=3;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
           dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_C2MouseClicked

    private void D2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D2MouseClicked
        // TODO add your handling code here:
           clickEvents.section="D";
        clickEvents.semester=3;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
         dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_D2MouseClicked

    private void F2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F2MouseClicked
        // TODO add your handling code here:
           clickEvents.section="F";
        clickEvents.semester=3;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
         dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_F2MouseClicked

    private void A3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A3MouseClicked
        // TODO add your handling code here:
           clickEvents.section="A";
        clickEvents.semester=5;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
         dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_A3MouseClicked

    private void B3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B3MouseClicked
        // TODO add your handling code here:
           clickEvents.section="B";
        clickEvents.semester=5;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
         dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_B3MouseClicked

    private void C3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C3MouseClicked
        // TODO add your handling code here:
         clickEvents.section="C";
        clickEvents.semester=5;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
         dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_C3MouseClicked

    private void D3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D3MouseClicked
        // TODO add your handling code here:
         clickEvents.section="D";
        clickEvents.semester=5;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
     dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_D3MouseClicked

    private void F3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F3MouseClicked
        // TODO add your handling code here:
         clickEvents.section="F";
        clickEvents.semester=5;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
     dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_F3MouseClicked

    private void A4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_A4MouseClicked
        // TODO add your handling code here:
         clickEvents.section="A";
        clickEvents.semester=7;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
     dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_A4MouseClicked

    private void B4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_B4MouseClicked
        // TODO add your handling code here:
        clickEvents.section="B";
        clickEvents.semester=7;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
     dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_B4MouseClicked

    private void C4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_C4MouseClicked
        // TODO add your handling code here:
        clickEvents.section="C";
        clickEvents.semester=7;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
     dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_C4MouseClicked

    private void D4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_D4MouseClicked
        // TODO add your handling code here:
        clickEvents.section="D";
        clickEvents.semester=7;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
     dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_D4MouseClicked

    private void F4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_F4MouseClicked
        // TODO add your handling code here:
        clickEvents.section="F";
        clickEvents.semester=7;
        jdbcConnect j1= new jdbcConnect();
        j1.connect();
        j1.executeSql();
        
     dispose();
        SectionData d1= new SectionData();
          
        d1.show();
       d1.DefaultClick().doClick();
    }//GEN-LAST:event_F4MouseClicked

    private void ProfCountComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_ProfCountComponentAdded
        // TODO add your handling code here:
    
    }//GEN-LAST:event_ProfCountComponentAdded

    private void AssoCountComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_AssoCountComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AssoCountComponentAdded

    private void AssistCountComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_AssistCountComponentAdded
        // TODO add your handling code here:
        
    }//GEN-LAST:event_AssistCountComponentAdded

    private void ProfCountComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_ProfCountComponentShown
        // TODO add your handling code here:
        
    }//GEN-LAST:event_ProfCountComponentShown

    private void ProfCountHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_ProfCountHierarchyChanged
        // TODO add your handling code here:
         ProfCount.setText(""+assignInvigDAO.count[2]);
    }//GEN-LAST:event_ProfCountHierarchyChanged

    private void AssoCountHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_AssoCountHierarchyChanged
        // TODO add your handling code here:
         AssoCount.setText(""+assignInvigDAO.count[1]);
    }//GEN-LAST:event_AssoCountHierarchyChanged

    private void AssistCountHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_AssistCountHierarchyChanged
        // TODO add your handling code here:
         AssistCount.setText(""+assignInvigDAO.count[0]);
    }//GEN-LAST:event_AssistCountHierarchyChanged

    private void BranchFieldHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_BranchFieldHierarchyChanged
        // TODO add your handling code here:
        BranchField.setText("Branch: "+Dashboard_1.subjectVariables.subject);
    }//GEN-LAST:event_BranchFieldHierarchyChanged

    private void TotalInvigHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_TotalInvigHierarchyChanged
        // TODO add your handling code here:
        int total=assignInvigDAO.count[0]+assignInvigDAO.count[1]+assignInvigDAO.count[2];
        TotalInvig.setText(""+total);
    }//GEN-LAST:event_TotalInvigHierarchyChanged
  static String Designation;
    private void AllInvigilatorsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AllInvigilatorsMouseClicked
        // TODO add your handling code here:
        
       InivigilatorList gAll = new InivigilatorList();
       gAll.connect();
       gAll.initializeQuery();
       gAll.listPopulateAll();
       Designation="All Invigilators";
       dispose();
       gAll.show();
        
    }//GEN-LAST:event_AllInvigilatorsMouseClicked

    private void InvigProfMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvigProfMouseClicked
        // TODO add your handling code here:
         InivigilatorList gProf = new InivigilatorList();
         gProf.connect();
       gProf.initializeQuery();
       gProf.listPopulateProf();
     Designation="Professor Invigilators";

        dispose();
       gProf.show();
    }//GEN-LAST:event_InvigProfMouseClicked

    private void InvigAssoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvigAssoMouseClicked
        // TODO add your handling code here:
       InivigilatorList gAsso = new InivigilatorList();
       gAsso.connect();
       gAsso.initializeQuery();
       gAsso.listPopulateAsso();
     Designation="Associate Invigilators";

        dispose();
       gAsso.show();
    }//GEN-LAST:event_InvigAssoMouseClicked

    private void InvigAssistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InvigAssistMouseClicked
        // TODO add your handling code here:
        InivigilatorList gAssist = new InivigilatorList();
        gAssist.connect();
       gAssist.initializeQuery();
       gAssist.listPopulateAssist();
      Designation="Assistant Invigilators";

        dispose();
       gAssist.show();
    }//GEN-LAST:event_InvigAssistMouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
         dispose();
        ExamSchedule s1=new ExamSchedule();
        s1.show();
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
         dispose();
        SectionData s1=new SectionData();
        s1.show();
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
       
      
        
            
        
        
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard_2().setVisible(true);
            }
        });
    }
    
    
   
    
    
    class clickEvents{
    static  String section;
    static int semester;
     static String sectionCoordinator;
     static String[] examDate= new String[20];
     static String[] examName = new String[20]; //update to number of subjects
     static  String[] invig = new String[3]; //Any number of exams still 3 groups/section so 3 invigilators   
    
    }  
     
     class sqlQueries{
         
        
         //Query for section coordinator in SectionData
         static String profQuery="Select professor.prof_name FROM professor WHERE professor.prof_id=(Select distinct students.sec_coord_id From students WHERE students.section='"+clickEvents.section+"' and semester='"+clickEvents.semester+"' and branch='"+Dashboard_1.subjectVariables.subject+"')";
         
         //Query for exam dates in section data--> Fetches 3/6 exam dates for a particular branch and year/semester.
         static String examDateQuery="Select distinct exam_date from ExamTT Where batch_year ="+clickEvents.semester;
          
         
        
         
         
         static String [] examNameQueries = new String[6]; //update to number of subjects
          static void examQueries()
         {
             //NOTE: CHANGE THIS TO 6 AFTER YOU'VE ADDED ALL SUBJECTS 
             //Query for subject names 
             for(int i=0;i<6;i++)
             {  int x=i+1;
              
               //While entering Time table Format for course code: branch + 2 + semester + 01/02/03....
                examNameQueries[i]= "Select sub_name from ExamTT where sub_code='"+ Dashboard_1.subjectVariables.subject + "_2" + clickEvents.semester+"0" +x+"'" ;
     
             }
         }
          
         static String [] examInvigQueries = new String[18];
         static void invigQueries(){
         
             
         //fetch invigilators already assigned in Year_2 table --> we will get 3 invigilators (1 for each group)
         for(int i=0;i<3;i++)
         {
             
             String s = clickEvents.section.toLowerCase();
          
              int x=i+1;
             examInvigQueries[i]="Select prof_name from professor WHERE prof_id= (SELECT sec_"+ s  + x +" FROM Year_2 Where semester='"+clickEvents.semester+"' and branch='"+Dashboard_1.subjectVariables.subject+"')"; 
         }
         
         
         
         
     }
         
  }
     
     
     
       
       
     
     
     
     //Toconnect to database
     class jdbcConnect{
         Connection con=null;
       public void connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbc","Jaimin","Jaimin@2001");
        } catch(Exception e){
       System.out.println(e);
          }
       }
       
      //To prepare data for SectionData form fetching all the necessary details
         public void executeSql(){
            Statement st = null;
            ResultSet rs=null;
         try{
         st= con.createStatement();
         
         }catch(Exception e){
             System.out.println(e);
         }
            
              //Fetch section coordinator for clicked section button
             try {
                 rs= st.executeQuery(sqlQueries.profQuery);
                 rs.next();
                 clickEvents.sectionCoordinator=rs.getString(1);
  
                 
                 
                //Executing this query gives n exam dates which are saved in clickEvents to display in SectionData
                  rs= st.executeQuery(sqlQueries.examDateQuery);
                  int p=0;
                 while(rs.next()){
                 clickEvents.examDate[p++]=rs.getString(1);
                 }
                 
                 //This query fetches all the exam names as per time table
                 sqlQueries.examQueries();
                
                 for(int i=0;i<sqlQueries.examNameQueries.length;i++)
                 { 
                  rs= st.executeQuery(sqlQueries.examNameQueries[i]);
                 rs.next();
                 
                 clickEvents.examName[i]=rs.getString(1);
                 }
                 
                 //This query is responsible for accessing invigilator names as assigned from Year_2
                 sqlQueries.invigQueries();
                 for(int i=0;i<3;i++)
                 {
                  rs= st.executeQuery(sqlQueries.examInvigQueries[i]);
                 rs.next();
                 clickEvents.invig[i]=rs.getString(1);
                 }
                 
                 //Testing purpose
                 for(int i=0;i<3;i++)
                 {
                     System.out.println(clickEvents.invig[i]);
                 }
                 
                 
             } catch (SQLException e) {
                System.out.println("pROBLEM HERE");
                System.out.println(e);
             }
           
            
        }
    
       
}  

        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton AllInvigilators;
    private javax.swing.JTextField AssistCount;
    private javax.swing.JTextField AssoCount;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JTextField BranchField;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton InvigAssist;
    private javax.swing.JButton InvigAsso;
    private javax.swing.JButton InvigProf;
    private javax.swing.JTextField ProfCount;
    private javax.swing.JTextField TotalInvig;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
