/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineexam;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author apple
 */
public class IndividualStudentGroup extends javax.swing.JFrame {

    /**
     * Creates new form IndividualStudentGroup
     */
    public IndividualStudentGroup() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        Group_1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        Group = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        Semester = new javax.swing.JTextField();
        SectionName = new javax.swing.JTextField();
        BranchName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Group_1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        Group_1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(Group_1);

        jPanel1.setBackground(new java.awt.Color(0, 255, 204));

        Group.setBackground(new java.awt.Color(0, 153, 153));
        Group.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        Group.setForeground(new java.awt.Color(255, 255, 255));
        Group.setText("Group ");
        Group.setBorder(null);
        Group.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                GroupHierarchyChanged(evt);
            }
        });
        Group.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GroupActionPerformed(evt);
            }
        });

        jButton2.setText("<--");

        jButton1.setText("-->");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Group, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Group, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTextField1.setBackground(new java.awt.Color(0, 255, 204));
        jTextField1.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField1.setText("Branch");

        jTextField2.setBackground(new java.awt.Color(0, 255, 204));
        jTextField2.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField2.setText("Section");

        jTextField3.setBackground(new java.awt.Color(0, 255, 204));
        jTextField3.setFont(new java.awt.Font("Trebuchet MS", 0, 18)); // NOI18N
        jTextField3.setText("Semester");

        Semester.setBackground(new java.awt.Color(0, 153, 153));
        Semester.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        Semester.setForeground(new java.awt.Color(255, 255, 255));
        Semester.setText("jTextField5");
        Semester.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                SemesterHierarchyChanged(evt);
            }
        });

        SectionName.setBackground(new java.awt.Color(0, 153, 153));
        SectionName.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        SectionName.setForeground(new java.awt.Color(255, 255, 255));
        SectionName.setText("jTextField5");
        SectionName.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                SectionNameHierarchyChanged(evt);
            }
        });

        BranchName.setBackground(new java.awt.Color(0, 153, 153));
        BranchName.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        BranchName.setForeground(new java.awt.Color(255, 255, 255));
        BranchName.setText("jTextField5");
        BranchName.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                BranchNameHierarchyChanged(evt);
            }
        });
        BranchName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BranchNameActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SectionName, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BranchName, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(SectionName, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Semester, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void GroupHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_GroupHierarchyChanged
        // TODO add your handling code here:
        Group.setText(" Group :  "+ SectionData.group);
    }//GEN-LAST:event_GroupHierarchyChanged

    private void GroupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GroupActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GroupActionPerformed

    private void BranchNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BranchNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BranchNameActionPerformed

    private void BranchNameHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_BranchNameHierarchyChanged
        // TODO add your handling code here:
        BranchName.setText(" "+  Dashboard_1.subjectVariables.subject);
    }//GEN-LAST:event_BranchNameHierarchyChanged

    private void SectionNameHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_SectionNameHierarchyChanged
        // TODO add your handling code here:
        SectionName.setText(" "+  Dashboard_2.clickEvents.section);
    }//GEN-LAST:event_SectionNameHierarchyChanged

    private void SemesterHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_SemesterHierarchyChanged
        // TODO add your handling code here:
        Semester.setText(" "+  Dashboard_2.clickEvents.semester);
    }//GEN-LAST:event_SemesterHierarchyChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IndividualStudentGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IndividualStudentGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IndividualStudentGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IndividualStudentGroup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IndividualStudentGroup().setVisible(true);
            }
        });
    }
    
      Connection con=null;
    public void connect(){
        
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbc","Jaimin","Jaimin@2001");
        } catch(Exception e){
       System.out.println(e);
    }
    }
       PreparedStatement pst; 
       int count=0;
      public void count(){  
        String countQuery ="Select COUNT(stu_id) from students where section='"+Dashboard_2.clickEvents.section+"' AND branch='"+Dashboard_1.subjectVariables.subject+"'";
        
        
        try{
         pst= con.prepareStatement(countQuery);
         ResultSet rs= pst.executeQuery();
         rs.next();
          count = rs.getInt(1);
         
         }catch(Exception e){
             System.out.println(e);
         }
      }
      
      
       String GroupQuery;
      public void group1(){
         GroupQuery = "Select stu_id,stu_name,stu_mail from students where section='"+Dashboard_2.clickEvents.section+"' AND branch='"+Dashboard_1.subjectVariables.subject+"' AND semester='"+Dashboard_2.clickEvents.semester+"' LIMIT "+(count/3);

            try{
         pst= con.prepareStatement(GroupQuery);
         ResultSet rs= pst.executeQuery();
       
         Group_1.setModel(DbUtils.resultSetToTableModel(rs));
        
         
         }catch(Exception e){
             System.out.println(e);
         }
      }  
      
      
        
      public void group2(){
      GroupQuery = "Select stu_id,stu_name,stu_mail from students where section='"+Dashboard_2.clickEvents.section+"' AND branch='"+Dashboard_1.subjectVariables.subject+"' AND semester='"+Dashboard_2.clickEvents.semester+"' LIMIT "+(count/3)+","+(count/3);
        try{
         pst= con.prepareStatement(GroupQuery);
         ResultSet rs= pst.executeQuery();
       
         Group_1.setModel(DbUtils.resultSetToTableModel(rs));
        
         
         }catch(Exception e){
             System.out.println(e);
         }
      }
        
        public void group3(){
        GroupQuery = "Select stu_id,stu_name,stu_mail from students where section='"+Dashboard_2.clickEvents.section+"' AND branch='"+Dashboard_1.subjectVariables.subject+"' AND semester='"+Dashboard_2.clickEvents.semester+"' LIMIT "+((count*2)/3)+","+count;
         try{
         pst= con.prepareStatement(GroupQuery);
         ResultSet rs= pst.executeQuery();
       
         Group_1.setModel(DbUtils.resultSetToTableModel(rs));
        
         
         }catch(Exception e){
             System.out.println(e);
         }
        }
   
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BranchName;
    private javax.swing.JTextField Group;
    private javax.swing.JTable Group_1;
    private javax.swing.JTextField SectionName;
    private javax.swing.JTextField Semester;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables
}
