/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package onlineexam;

import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author apple
 */
public class InivigilatorList extends javax.swing.JFrame {

    /**
     * Creates new form InivigilatorList
     */
    public InivigilatorList() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        InvigTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        ListTitle = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        InvigTable.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N
        InvigTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        InvigTable.setCellSelectionEnabled(true);
        InvigTable.setGridColor(new java.awt.Color(0, 153, 153));
        jScrollPane1.setViewportView(InvigTable);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        ListTitle.setFont(new java.awt.Font("Trebuchet MS", 1, 36)); // NOI18N
        ListTitle.setForeground(new java.awt.Color(255, 255, 255));
        ListTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ListTitle.setText("jLabel1");
        ListTitle.addHierarchyListener(new java.awt.event.HierarchyListener() {
            public void hierarchyChanged(java.awt.event.HierarchyEvent evt) {
                ListTitleHierarchyChanged(evt);
            }
        });

        jButton2.setText("<--");

        jButton1.setText("-->");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(ListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 447, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ListTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ListTitleHierarchyChanged(java.awt.event.HierarchyEvent evt) {//GEN-FIRST:event_ListTitleHierarchyChanged
        // TODO add your handling code here:
             ListTitle.setText(Dashboard_2.Designation);

        
    }//GEN-LAST:event_ListTitleHierarchyChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InivigilatorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InivigilatorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InivigilatorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InivigilatorList.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InivigilatorList().setVisible(true);
            }
        });
    }
    
    Connection con=null;
    public void connect() {
        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            con= DriverManager.getConnection("jdbc:mysql://localhost:3306/jdbc","Jaimin","Jaimin@2001");
        } catch(Exception e){
       System.out.println(e);
    }
    }
        
    
    
    PreparedStatement pst;
    String query= "Select prof_id,prof_name,prof_mail,contact_no from professor where prof_id IN(";
    
    public void initializeQuery(){
        for(int i=0;i<54;i++){
              
            
            if(i==53)
            {
                query=query.concat(String.valueOf(assignInvigDAO.invigCount[i])+")");
            }else{
                query=query.concat(String.valueOf(assignInvigDAO.invigCount[i])+",");
            }
           }
         System.out.println(query);  //Testing purpose
    } 
       public void listPopulateAll(){

          ResultSet rs=null;
        try {
            pst=con.prepareStatement(query);
            rs = pst.executeQuery();
        } catch (SQLException ex) {
            Logger.getLogger(InivigilatorList.class.getName()).log(Level.SEVERE, null, ex);
        }
          InvigTable.setModel(DbUtils.resultSetToTableModel(rs));
          
       }
       
     
       public void listPopulateProf(){
           query = query +" And designation='Professor'";
       ResultSet rs=null;
       
        try {
            pst=con.prepareStatement(query);
            rs = pst.executeQuery(query);
        } catch (SQLException ex) {
            Logger.getLogger(InivigilatorList.class.getName()).log(Level.SEVERE, null, ex);
        }
          InvigTable.setModel(DbUtils.resultSetToTableModel(rs));
     }
       public void listPopulateAssist(){
            query = query +" And designation='Assistant'";
       ResultSet rs=null;
        try {
            pst=con.prepareStatement(query);
            rs = pst.executeQuery(query);
        } catch (SQLException ex) {
            Logger.getLogger(InivigilatorList.class.getName()).log(Level.SEVERE, null, ex);
        }
          InvigTable.setModel(DbUtils.resultSetToTableModel(rs));
     }
       public void listPopulateAsso(){
            query = query +" And designation='Associate'";
       ResultSet rs=null;
        try {
            pst=con.prepareStatement(query);
            rs = pst.executeQuery(query);
        } catch (SQLException ex) {
            Logger.getLogger(InivigilatorList.class.getName()).log(Level.SEVERE, null, ex);
        }
          InvigTable.setModel(DbUtils.resultSetToTableModel(rs));
     }

       
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable InvigTable;
    private javax.swing.JLabel ListTitle;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
